Add
kosmos30732/BigBool pull request #1
Opened 2020-04-22 07:39 UTC by kosmos30732

2020-05-10 09:15 UTC, yalegko requested changes

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +    for (int j = 0; j < size_of_shift; j++)
Сдвигать большой вектор сдвигами по 1 это как-то уж слишком неэффективно.

Классический вариант: один цикл, который перекладывает базы+делает в них сдвиги за один пробег, либо два цикла, один сдвигает базы, второй делает сдвиги внутри баз

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +        return ERR_BIG_SHIFT;
errno переменные удобно использовать, когда не хочется усложнять сигнатуру функции отдельным аргументом для результата.

Например, `fopen` возвращает FILE* и потому сообщает об ошибке через NULL в результате + errno. Конструкция `status = fopen("file.txt", "r", &file)` была бы менее выразительна при использовании (но тем не менее есть огромное количество бибилотек, которые всегда возвращают статус, а результаты отдают по указателям)

То есть если есть возможность вернуть статус, то явно указываются (в комментариях) статусы, которые может вернуть функция и что они означают, а errno не выставляется.

Если вариантов вернуть статус нет (не хочется усложнять сигнатуру функции), то пишется что функция вернёт в случае ошибки (обязательно!), e.g. NULL у `fopen` и какие статусы errno она выствляет и в каком случае

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +        if (string[ind_string] == '1' || string[ind_string] == '0')
Всегда имеет смысл проверять более короткую ветку условий: код от этого становится сильно читаемее, так как уходит лишняя вложенность

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +            return NULL;
Вот это как раз пример функции, где стоит использовать `errno` (либо возвращать результат по указателю и сделать статусы)

Пользователь должен явно понимать что не так с его входными данными.

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +                vector->parts[0] |= (1 << 0);
А почему 1<<0 а не 1?)

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +            need_shift = 1;
Наверное можно попробовать обработать первый бит отдельно и тогда цикл станет аккуратнее 🤔

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +    char* string = malloc ((ind_string + 1) * sizeof (char));
По-хорошему надо проверить что память выделилась, иначе можно неприятно упасть на обращении по NULL

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +        }
Можно немного побыть хардовым сишником и сделать 

```c
char bit = vector->parts[vector->last_part]&(1<<i);
string[ind_string] = '0' + bit;
```

:)

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +        string = (char*)realloc (string, (ind_string + 1) * sizeof (char));
Совершенно лишнее, ты ведь и так знаешь сколько тебе символов понадобится

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +    int ind_string = 0;
Стандартное сокращение для индекса вне цикла -- `idx`.

Ещё в английском важен порядок слов, поэтому согласование `признак + предмет` надо писать именно в таком порядке, т.е. `string_idx`

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +    }
Предполагается, что мы как и в математике можем представлять "ведущие нули" у коротких векторов и дизъюнкцию можно делать у векторов разного размера

```
10101 | 1010 == 11111
```

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +    vector->last_part = vector1->last_part;
Вполне понимаю соблазн вернуть результат операции в return, но вот таким образом нам придётся следить за всеми результатами и делать free на каждый, что практически нереально а цепочках операций, e.g

```c
bb_xor(bb_conjunction(bb_from_string("10101"), bb_from_string("111")), bb_from_string("101010101"))
```

В данной конкретной работе у нас есть ограничение по максимальному размеру вектора, поэтому можно просто вернуть саму структуру со стека и она будет скопирована компилятором (тк буффер статический и полностью содержится в структуре)

2020-05-10 09:15 UTC, yalegko commented on bb.c
> +    {
Также: сдвигать по 1 биту так себе затея. Лучше обойтись одним-двумя циклами.

Кроме того можно хитро обойти уже имеющимися операциями и почти не писать код сдвига :)

2020-05-10 09:15 UTC, yalegko commented on bb.h
> +int left_shift (bb* vector, int size_of_shift); //makes a left shift by size_of_shift and return zero in case of successful execution
Комментарии к функциям пишут сверху, часто в multi-line комменте. 

Помимо того, что делает и что принимает, обязательно дописать возвращаемые значения, особенно при ошибках. Плюс стоит описать кто владеет возвращаемой памятью. Например, если функция возвращает bb* то надо писать должен ли пользователь эту память очищать и как

Места где можно сразу посмотреть чтобы всё было хорошо я чёт сходу придумать не могу, но вот пара приличных ссылок:
- Достаточно неплохая либа на Си, которой я пользовался не давно. Не супер читаемо, но инфы в комменте хватает: https://github.com/libyal/libregf/blob/master/include/libregf.h.in
- Секция Function comments тут: https://www.cs.swarthmore.edu/~newhall/unixhelp/c_codestyle.html
- Как пример того, что стоит указать при описании функции: https://en.cppreference.com/w/c/io/fopen

2020-05-10 10:36 UTC, kosmos30732 commented on bb.c
> +    for (int j = 0; j < size_of_shift; j++)
А подробнее можно? не могу врубиться что за переложение баз... Под базой понимать байт который сдвинется на другой байт

2020-05-10 10:36 UTC, kosmos30732 commented on bb.c
> +        if (string[ind_string] == '1' || string[ind_string] == '0')
Так я всего лишь проверяю наличие 1 или 0 он и так короткий, как еще его укоротить?

2020-05-10 10:36 UTC, kosmos30732 commented on bb.c
> +                vector->parts[0] |= (1 << 0);
Потому что в parts'ы биты записываются от 0 до 7

2020-05-10 10:36 UTC, kosmos30732 commented on bb.c
> +        }
Это обязательно именно так?

2020-05-10 10:39 UTC, yalegko commented on bb.c
> +    for (int j = 0; j < size_of_shift; j++)
Сдвиг базы -- когда i-й элемент двигается на j-ю позицию
Сдвиг внутри базы -- сдвиг битов внутри одного элемента массива.

В рамках текущей лабы можно просто читать "база" как байт, но как я уже говорил на паре, реализация больших чисел эффективнее с большими базами, uint32/uint64

2020-05-10 10:40 UTC, yalegko commented on bb.c
> +        if (string[ind_string] == '1' || string[ind_string] == '0')
Не условие, а сами ветки. 

```c
if (!ok) 
{
    return STATUS_NOK;
}
// continue stuff
```

2020-05-10 10:41 UTC, yalegko commented on bb.c
> +                vector->parts[0] |= (1 << 0);
`1<<0 == 1`

2020-05-10 10:53 UTC, kosmos30732 commented on bb.h
> +int left_shift (bb* vector, int size_of_shift); //makes a left shift by size_of_shift and return zero in case of successful execution
А в самих функциях можно добавить чистку и прыгать goto?

2020-05-10 10:58 UTC, yalegko commented on bb.h
> +int left_shift (bb* vector, int size_of_shift); //makes a left shift by size_of_shift and return zero in case of successful execution
> А в самих функциях можно добавить чистку и прыгать goto?

Если это необходимо, то да. Как я и говорит - необходимость очистки ресурсов при выходе во время ошибки один из нормальных юзкейсов goto

2020-05-10 11:50 UTC, kosmos30732 commented on bb.c
> +    }
При создании векторы все равно нулями заполняются, тогда есть смысл нули вручную дописывать до максимальной из двух длин векторов? или просто тогда оставить строки 270-273?

2020-05-17 13:30 UTC, yalegko requested changes
Не считая пары мелочей код выглядит очень здорово.

Самое время написать тесты и проверить рабочий ли он и удобно ли им пользоваться :)

2020-05-17 13:30 UTC, yalegko commented on bb.h
> +#define legth_of_parts 20
Дефайны всегда пишет ALL_CAPS чтобы было явно видно что это константа. Иначе можно как я сейчас сидеть понимать что произошло и откуда взялась переменная

2020-05-17 13:30 UTC, yalegko commented on bb.h
> +extern int bb_errno;
Чтобы было совсем хорошо, можно сделать отдельный тип для статусов и возвращать его из функций.

Это обычно сильно помогает понять где возвращается статус, а где просто число (ну и в целом type-safety -- круто)

2020-05-17 13:30 UTC, yalegko commented on bb.c
> +			vector->parts[0] |= (string[string_idx]-48);
Если где-то ты делаешь арифметику с кодом символа, то всегда пиши именно символ, а не числовой код. 

`string[string_idx]-'0'`

2020-05-17 13:30 UTC, yalegko commented on bb.c
> +		if (string[0]=='1')
Через `&&` наверное смотрелось бы аккуратнее)

2020-05-17 13:30 UTC, yalegko commented on bb.c
> +    char* string = calloc (1,(vector->last_part*8+vector->last_bit) * sizeof (char));
0-байт кажется не посчитал

2020-05-17 13:30 UTC, yalegko commented on bb.c
> +    }
Если ты уверен, что всегда, когда вектор уменьшается, его старые разряды заполняются нулями, то можно явно не описывать этот кейс.

Но это потенциально место для бага

2020-05-17 13:30 UTC, yalegko commented on bb.c
> +    vector->last_part = vector1->last_part;
Вопрос о динамической памяти всё ещё открыт. С аллокацией в каждой процедуре имхо медленно делать операции и сложно следить за тем, чтобы память не текла.

Это не требование, но сразу предупреждаю, что с текущим вариантом в тестах буду пристально следить, чтобы вся память была почищена

2020-05-17 13:30 UTC, yalegko commented on bb.c
> +    if (vector2->last_part * 8 + vector2->last_bit > vector1->last_part * 8 + vector1->last_bit)
Я бы сделал инлайн-функцию для получения длины в битах и пользовался тут ей, было бы весьма читаемо и красиво

2020-05-17 13:30 UTC, yalegko commented on bb.c
> +    bb* new_vector = bb_disjunction (new_vector1, new_vector2);
Не проверяешь ретёрны/статусы операций

2020-05-18 05:38 UTC, kosmos30732 commented on bb.c
> +    bb* new_vector = bb_disjunction (new_vector1, new_vector2);
А как их лучше проверить: После вызова проверить что bb_errno == ERR_OK и идти дальше, а если нет то что.... новую ошибку создать типа ERR_WITH_LEFT_CYCLE? Или вовсе проверять каждую ошибку после каждой функции и если она равна этой возвращать эту же ошибку и NULL?

2020-05-18 05:43 UTC, kosmos30732 commented on bb.c
> +    char* string = calloc (1,(vector->last_part*8+vector->last_bit) * sizeof (char));
нет, он включен

2020-05-19 10:46 UTC, yalegko requested changes

2020-05-19 10:46 UTC, yalegko commented on bb.c
> +    free (new_vector1);
В виндовс-библиотеках часто встречается вариант

```c
cleanup:
     if (new_vector != NULL) free(new_vector);
     if (new_vector2 != NULL) free(new_vector2);
```

Но на твой вкус

2020-05-19 10:46 UTC, yalegko commented on bb.c
> +    if (bb_errno!=ERR_OK)
Кажется у тебя API говорит проверять errno только в случае нулевого результата

2020-05-19 10:46 UTC, yalegko commented on tests.c
> +	}
Приватные штуки типа того как вектор реально лежит в памяти обычно не тестируют. 

Чтобы это проверить стоит сделать конструктор от `uint64_t` и сравнивать два конструктора между собой

2020-05-19 10:46 UTC, yalegko commented on tests.c
> +	}
Напрашивается разбиение на отдельные функции (тест-кейсы), проверяющие конкретные блоки кода (конструкторы, сдвиги, ошибки)

2020-05-19 10:46 UTC, yalegko commented on tests.c
> +	}
Тесты, как правило, пишутся таким образом, чтобы показать пользователю примеры правильного использования библиотеки.

Сейчас они написаны так, что память, выделенная на куче, никогда не освобождается, что является грубой ошибкой.

Нужно или пересмотреть способ возврата вектора из функций, либо чистить всю выделяемую память

2020-05-19 10:46 UTC, yalegko commented on tests.c
> +	}
Напрашивается какой-нибудь макрос/функция типа 

```c 
int bb_eq_str(bb_inversion (bb_from_string ("1011001")), "0100110")
```

2020-05-24 09:15 UTC, yalegko requested changes

2020-05-24 09:15 UTC, yalegko commented on tests.c
> +	vec1 = bb_from_uint64_t (1573815);
Вроде число можно записать прям в бинарной СС: https://gcc.gnu.org/onlinedocs/gcc/Binary-constants.html

Если нет, то лучше обычно предпочесть 16-чную, у читателя появится небольшой шанс перевести его в биты "на глаз"

2020-05-24 09:15 UTC, yalegko commented on tests.c
> +	bb* vec = bb_from_string ("100001010100110101");
Хорошо бы ещё проверить corner cases, например, что вектор можно "сдвинуть направо" до 0.

Сдвинуть налево целиком во все 0 (типа 1 << 100) в твоей реализации не получится, да?

2020-05-24 09:15 UTC, yalegko commented on tests.c
> +int main ()
Помимо чистых юнит-тестов имеет смысл сделать тесты, которые генерируют случайные входные данные и потом проверяют какие-то булевы тождества, например, `(x & ~x) == 0`, сдвиги сначала влево, а потом вправо тоже приводят к оригинальному результату, можно выразить XOR через булев базис и проверять его

2020-05-31 07:30 UTC, yalegko approved these changes
Отлично, зачтено

2020-05-31 07:30 UTC, yalegko commented on tests.c
> +int tests_with_random ()
В несколько отдельных функций в комментариями какое именно тождество проверяется было бы читаемее

2020-05-31 09:49 UTC, merged